import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { HumiLogo } from "@/components/humi/HumiLogo";
import { OrbitBackdrop } from "@/components/humi/OrbitGraphic";
import { HumiWelcomeHero } from "@/components/humi/HumiWelcomeHero";
import { SignupForm } from "@/components/humi/SignupForm";
import { ResumeUpload } from "@/components/humi/ResumeUpload";
import { ResumeParsingLoader } from "@/components/humi/ResumeParsingLoader";
import { ResumeSummary } from "@/components/humi/ResumeSummary";
import { CareerInterestForm } from "@/components/humi/CareerInterestForm";
import { CareerEvolutionReport } from "@/components/humi/CareerEvolutionReport";
import { GeneratingStages } from "@/components/humi/GeneratingStages";
import { CandidateAuth } from "@/components/humi/CandidateAuth";
import { submitLead, getMyReport } from "@/lib/api/leads.functions";
import {
  analyzeResume,
  generateCoreStage,
  generateResumeFeedbackStage,
  generateRolesAndPlanStage,
  generateFallbackReport,
} from "@/lib/api/analysis.functions";
import { assembleReport } from "@/lib/humi/report-assembly";
import { saveProfile } from "@/lib/humi/candidate-profile";
import type { Counselling } from "@/lib/humi/counselling";
import type { CoreReportOutput, ResumeFeedbackOutput, RolesAndPlanOutput } from "@/lib/ai/schemas";
import type {
  InterestData,
  ParsedResume,
  Recommendation,
  Report,
  ResumeInput,
  SignupData,
} from "@/lib/humi/types";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Humi.ai — Discover Your AI Career Evolution" },
      {
        name: "description",
        content:
          "Upload your resume and get a personalized AI career evolution report: future-ready role, skills to learn, AI tools, and a 30-60-90 day learning path.",
      },
      { property: "og:title", content: "Humi.ai — Transform Your Career" },
      {
        property: "og:description",
        content:
          "A personalized AI career evolution report for job fair candidates, students, professionals and career switchers.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: HumiApp,
});

type Step =
  | "welcome"
  | "login"
  | "signup"
  | "upload"
  | "parsing"
  | "summary"
  | "interest"
  | "generating"
  | "report";

function HumiApp() {
  const [step, setStep] = useState<Step>("welcome");
  const [signup, setSignup] = useState<SignupData | null>(null);
  const [signupPrefill, setSignupPrefill] = useState<Partial<SignupData>>();
  const [resumePrefill, setResumePrefill] = useState<Partial<ResumeInput>>();
  const [parsed, setParsed] = useState<ParsedResume | null>(null);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [report, setReport] = useState<Report | null>(null);
  const [counselling, setCounselling] = useState<Counselling | null>(null);
  const [resumeFile, setResumeFile] = useState<File | undefined>();

  // Each piece of the report is generated by its own independent AI call,
  // fired in parallel, so the UI can reveal each one — with its own short
  // "Continue" step — as soon as it resolves, instead of one long spinner
  // blocking on all three together.
  const [genStageIndex, setGenStageIndex] = useState<0 | 1 | 2>(0);
  const [pendingInterest, setPendingInterest] = useState<InterestData | null>(null);
  const [coreData, setCoreData] = useState<CoreReportOutput | null>(null);
  const [resumeFeedbackData, setResumeFeedbackData] = useState<ResumeFeedbackOutput | null>(null);
  const [rolesAndPlanData, setRolesAndPlanData] = useState<RolesAndPlanOutput | null>(null);
  const [genFailed, setGenFailed] = useState(false);

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [step]);

  const runParse = async (input: ResumeInput, who: SignupData, file?: File) => {
    setResumeFile(file);
    setStep("parsing");
    try {
      const { parsed: analyzed, recommendations: recs } = await analyzeResume({
        data: {
          resumeText: input.resumeText,
          manual: {
            recentRole: input.recentRole,
            experienceSummary: input.experienceSummary,
            keySkills: input.keySkills,
            industries: input.industries,
          },
          signup: who,
        },
      });
      setParsed({ ...analyzed, fileName: input.fileName });
      setRecommendations(recs);
      setStep("summary");
    } catch (err) {
      console.error("Failed to analyze resume", err);
      toast.error("Something went wrong analyzing your resume. Please try again.");
      setStep("upload");
    }
  };

  const finalizeReport = (
    built: Report,
    builtCounselling: Counselling,
    interestData: InterestData,
  ) => {
    if (!parsed || !signup) return;
    setReport(built);
    setCounselling(builtCounselling);

    saveProfile({
      firstName: signup.firstName,
      lastName: signup.lastName,
      email: signup.email,
      phone: signup.phone,
      familyKey: parsed.familyKey,
      primaryFunction: parsed.primaryFunction,
      currentRole: built.currentRole,
      futureRole: built.futureRole,
      skills: parsed.skills,
      interestRole: interestData.chosenRole,
    });

    const form = new FormData();
    form.set("firstName", signup.firstName);
    form.set("lastName", signup.lastName);
    form.set("email", signup.email);
    form.set("phone", signup.phone);
    form.set("careerStage", signup.careerStage || "Not specified");
    form.set("recommendedRole", built.futureRole);
    form.set("careerInterest", `${interestData.chosenRole} · ${interestData.industry}`);
    form.set("aiReadiness", String(built.aiReadiness));
    form.set("reportJson", JSON.stringify(built));
    form.set("counsellingJson", JSON.stringify(builtCounselling));
    form.set("parsedJson", JSON.stringify(parsed));
    if (resumeFile) form.set("resume", resumeFile);

    submitLead({ data: form }).catch((err) => {
      console.error("Failed to save candidate lead", err);
      toast.error("We couldn't save your submission, but your report is ready below.");
    });

    setStep("report");
  };

  const finish = (interestData: InterestData) => {
    if (!parsed || !signup) return;
    setStep("generating");
    setGenStageIndex(0);
    setCoreData(null);
    setResumeFeedbackData(null);
    setRolesAndPlanData(null);
    setGenFailed(false);
    setPendingInterest(interestData);

    const input = { data: { parsed, interest: interestData, signup } };

    generateCoreStage(input)
      .then((r) => (r.ok ? setCoreData(r.core) : setGenFailed(true)))
      .catch(() => setGenFailed(true));
    generateResumeFeedbackStage(input)
      .then((r) => (r.ok ? setResumeFeedbackData(r.resumeFeedback) : setGenFailed(true)))
      .catch(() => setGenFailed(true));
    generateRolesAndPlanStage(input)
      .then((r) => (r.ok ? setRolesAndPlanData(r.rolesAndPlan) : setGenFailed(true)))
      .catch(() => setGenFailed(true));
  };

  // Any single stage failing degrades the whole report together to the
  // deterministic engine, rather than mixing AI-quality and generic content.
  useEffect(() => {
    if (!genFailed || step !== "generating" || !parsed || !signup || !pendingInterest) return;
    generateFallbackReport({ data: { parsed, interest: pendingInterest, signup } })
      .then(({ report: built, counselling: builtCounselling }) =>
        finalizeReport(built, builtCounselling, pendingInterest),
      )
      .catch((err) => {
        console.error("Fallback report generation failed", err);
        toast.error("Something went wrong generating your report. Please try again.");
        setStep("interest");
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [genFailed]);

  const handleReturningLogin = async (loggedInEmail: string) => {
    try {
      const mine = await getMyReport();
      if (mine) {
        setSignup(mine.signup);
        setParsed(mine.parsed);
        setReport(mine.report);
        setCounselling(mine.counselling);
        setStep("report");
        return;
      }
    } catch (err) {
      console.error("Failed to load saved report", err);
    }
    setSignupPrefill({ email: loggedInEmail });
    toast.message("You're logged in — let's build your career report.");
    setStep("signup");
  };

  const continueGenerating = () => {
    if (genStageIndex < 2) {
      setGenStageIndex((i) => (i + 1) as 0 | 1 | 2);
      return;
    }
    if (!coreData || !resumeFeedbackData || !rolesAndPlanData || !pendingInterest) return;
    const { report: built, counselling: builtCounselling } = assembleReport(
      coreData,
      resumeFeedbackData,
      rolesAndPlanData,
      pendingInterest,
    );
    finalizeReport(built, builtCounselling, pendingInterest);
  };

  return (
    <main className="relative min-h-screen overflow-hidden">
      <OrbitBackdrop />
      <Toaster />

      <header className="sticky top-0 z-40 border-b border-border bg-background/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-3">
          <button onClick={() => setStep("welcome")} aria-label="Humi.ai home">
            <HumiLogo />
          </button>
          <div className="flex items-center gap-3">
            <Link
              to="/admin"
              className="text-xs font-semibold text-muted-foreground hover:text-primary"
            >
              Login
            </Link>
          </div>
        </div>
      </header>

      <AnimatePresence mode="wait">
        {step === "welcome" && (
          <HumiWelcomeHero
            key="welcome"
            onStart={() => setStep("signup")}
            onLogin={() => setStep("login")}
          />
        )}
        {step === "login" && (
          <CandidateAuth key="login" defaultMode="login" onAuthenticated={handleReturningLogin} />
        )}
        {step === "signup" && (
          <SignupForm
            key="signup"
            initial={signupPrefill}
            onSubmit={(d) => {
              setSignup(d);
              setStep("upload");
            }}
          />
        )}
        {step === "upload" && signup && (
          <ResumeUpload
            key="upload"
            initial={resumePrefill}
            onSubmit={(input, file) => runParse(input, signup, file)}
          />
        )}
        {step === "parsing" && <ResumeParsingLoader key="parsing" />}
        {step === "summary" && parsed && signup && (
          <ResumeSummary
            key="summary"
            parsed={parsed}
            signup={signup}
            recommendations={recommendations}
            onContinue={() => setStep("interest")}
          />
        )}
        {step === "interest" && (
          <CareerInterestForm key="interest" recommendations={recommendations} onSubmit={finish} />
        )}
        {step === "generating" && (
          <GeneratingStages
            key="generating"
            activeStage={genStageIndex}
            core={coreData}
            resumeFeedback={resumeFeedbackData}
            rolesAndPlan={rolesAndPlanData}
            onContinue={continueGenerating}
          />
        )}
        {step === "report" && report && counselling && parsed && signup && (
          <CareerEvolutionReport
            key="report"
            report={report}
            counselling={counselling}
            parsed={parsed}
            signup={signup}
            onRestart={() => {
              setStep("welcome");
              setReport(null);
              setCounselling(null);
              setParsed(null);
              setRecommendations([]);
              setSignup(null);

              setSignupPrefill(undefined);
              setResumePrefill(undefined);
              setResumeFile(undefined);

              setGenStageIndex(0);
              setPendingInterest(null);
              setCoreData(null);
              setResumeFeedbackData(null);
              setRolesAndPlanData(null);
              setGenFailed(false);
            }}
          />
        )}
      </AnimatePresence>

      <footer className="border-t border-border px-5 py-8 text-center text-xs text-muted-foreground">
        Humi.ai — Transform Your Career · Career guidance only, not a hiring decision.
      </footer>
    </main>
  );
}
